using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace RS_Lib
{
    /// <summary>
    /// 通用-遥感图像类
    /// </summary>
    public partial class RsImage
    {

        /// <summary>
        /// 构造BSQ-由byte产生新的遥感图像数据
        /// </summary>
        /// <param name="fn"></param>
        /// <param name="data"></param>
        public RsImage(string fn, byte[,,] data)
        {
            this.FileName = fn;
            DeepCopyData(data);
            ReadMetaData(data);
        }

        /// <summary>
        /// 由三维byte数组生成图像文件
        /// </summary>
        /// <param name="data"></param>
        private void ReadMetaData(byte[,,] data)
        {
            this.Interleave = "bsq";
            this.BandsCount = data.GetLength(0);
            this.Samples = data.GetLength(2);
            this.Lines = data.GetLength(1);
            this.Description = "{ Image Generated By Gp.A @ " +
                               DateTime.Now.ToString(CultureInfo.CurrentCulture) + "}";
            this.DataType = 1;
            this.XStart = 0;
            this.YStart = 0;
        }

        /// <summary>
        /// 深拷贝三维数组
        /// </summary>
        /// <param name="data"></param>
        private void DeepCopyData(byte[,,] data)
        {
            this._picData = new byte[
                data.GetLength(0),
                data.GetLength(1),
                data.GetLength(2)];

            for (int i = 0; i < data.GetLength(0); i++)
            {
                for (int j = 0; j < data.GetLength(1); j++)
                {
                    for (int k = 0; k < data.GetLength(2); k++)
                    {
                        this._picData[i, j, k] = data[i, j, k];
                    }
                }
            }

        }

    }
}
